default_platform(:ios)

platform :ios do

  before_all do 
    @podspec_name = "xolaniRabbitPod.podspec"
  end

  lane :release_current do
    version = version_get_podspec(path: @podspec_name)
    UI.message("#{version}")
     pod_lib_lint	
     pod_push
  end
end