default_platform(:ios)

platform :ios do

  before_all do 
    @podspec_name = "testPod.podspec"
  end

  lane :release_current do
    version = version_get_podspec(path: @podspec_name)
    if git_tag_exists(tag: version)
      UI.user_error!("The tag #{version} already exists on the repo. To release a new version of the library bump the version on #{@podspec_name}")
    end
    pod_lib_lint --allow-warnings
    add_git_tag(tag: "#{version}")
    push_git_tags
    pod_push
  end
end