default_platform(:ios)

platform :ios do

  before_all do 
    @podspec_name = "xolaniRabbitPod.podspec"
  end

  lane :release_current do
    version = version_get_podspec(path: @podspec_name)
    UI.message("#{version}")
    if !git_tag_exists(tag: version)
      pod_lib_lint
      add_git_tag(tag: "#{version}")
      push_git_tags(force: "true")	
      pod_push
    end
  end
end