
name: Create tag
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: xolani-xd95/podReleaseTest/.github/workflows/main.yml@main
      - name: test
        run: "echo testings"
