name: Bump version
on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
  workflow_call:
    inputs:
      bump_type: # "major", "minor" or "patch"
        required: true
        type: string
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true 
          
      - name: Bump podspec
        env:
          PODSPEC_BUMP_TYPE: ${{ inputs.bump_type }}
        run: | 
          cd .github
          bundle exec fastlane bump_podspec_ci
          
      - name: Commit changes
        run: |
          git config user.email "dlaminixolani440@gmail.com"
          git config user.name "xolani-xd95"
          git diff HEAD
          git add xolaniRabbitPod.podspec Podfile.lock
          git commit -m "Bump pod ${{ inputs.bump_type }} ${{ env.PODSPEC_BUMP_NEW_VERSION }}"
      
      - uses: actions/checkout@v3
       
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.PODSPEC_BUMP_NEW_VERSION }}',
              sha: context.sha
            })
