name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true 

      - name: Bump podspec
        env:
          PODSPEC_BUMP_TYPE: patch
        run: | 
          cd .github
          bundle exec fastlane bump_podspec_ci
          
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.env.PODSPEC_BUMP_NEW_VERSION }}',
              sha: context.sha
            })
